CREATE TABLE IF NOT EXISTS cameras (
  id SERIAL PRIMARY KEY,
  ip INET UNIQUE NOT NULL,
  nome TEXT NOT NULL,
  ativa BOOLEAN NOT NULL DEFAULT TRUE,
  pendente BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
